### ISSUE TITLE
Update broke ip-ban

### ISSUE THREAD

**Issue by gbrabelo** [Martlark/flask-ipban#16]
[2021-03-19 17:04:29 -0300] [29366] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "venv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "init_server.py", line 60, in <module>
    ip_ban = IpBan(persist=True, ban_count=2, record_dir=ip_ban_path, ip_header='X-Client-IP')
  File "venv/lib/python3.7/site-packages/flask_ipban/ip_ban.py", line 66, in __init__
    self.load_allowed()
  File "venv/lib/python3.7/site-packages/flask_ipban/ip_ban.py", line 461, in load_allowed
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'venv/lib/python3.7/site-packages/flask_ipban/allowed.yaml'

**Comment by Martlark** [comment]
Hmm.  I think I know what went wrong.

**Comment by Martlark** [comment]
I have fixed this in a new release.
